Structure
AbdelazizSoliman/Leaderboard pull request #2
Opened 2023-05-17 14:59 UTC by AbdelazizSoliman

In this pull request,

 I installed linters, webpack
 I Used ES6 modules, with import and export.

2023-05-17 15:11 UTC, DammyShittu requested changes
Hi @AbdelazizSoliman,

## Highlights
✔️ Webpack for app set up

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] When I ran your app I go this error page. Kindly set `mode` to "development" in your weback.config.js file

  ![ururu](https://github.com/AbdelazizSoliman/Leaderboard/assets/54848363/99dc7f49-f35a-4e38-bfec-d09d4be550f1)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 15:11 UTC, DammyShittu commented on src/styles.css
>  }
- [ ] Kindly improve your styling. Move the content of the wireframe to be closer to the top of the page so one does not need to scroll before one can see the page content.

  ![image](https://github.com/AbdelazizSoliman/Leaderboard/assets/54848363/ead340e1-4d4b-4481-8ca8-59ed9a1e9f23)

2023-05-17 15:58 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @AbdelazizSoliman 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 15:58 UTC, tresorsawasawa commented on package.json
>      "type": "git",
- [ ] As mentioned by the previous reviewer, kindly make sure you fix this error bellow when a user runs your application. Right now your application displays the below error:
![Screenshot from 2023-05-17 17-50-54](https://github.com/AbdelazizSoliman/Leaderboard/assets/83042742/bb5beb73-33cc-4c51-a4e1-3100ae974e20)

2023-05-18 06:11 UTC, AdnanOlarmmi approved these changes
Hi @AbdelazizSoliman,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- Fixed required changes.

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-18 06:27 UTC, merged